name: LiteTeam
version: 1.1.7
author: Himmelt
main: org.soraworld.team.LiteTeam
depend: [Violet]
softdepend: [Vault,Essentials,PlayerPoints,PlaceholderAPI,Residence]
website: https://github.com/Himmelt/LiteTeam
description: LiteTeam Plugin.
permissions:
  liteteam.admin:
    default: op
