name: TeamGuild
version: 1.1.3
author: Himmelt
main: org.soraworld.guild.TeamGuild
depend: [Violet]
softdepend: [Vault,Essentials,PlayerPoints]
website: https://github.com/Himmelt/TeamGuild
description: TeamGuild Plugin.
permissions:
  teamguild.admin:
    default: op
