name: TeamGuild
version: 1.7.10-1.0.2
author: Himmelt
main: org.soraworld.guild.TeamGuild
depend: [Violet]
softdepend: [Vault,Essentials,PlayerPoints,PlaceholderAPI]
website: https://github.com/Himmelt/TeamGuild
description: TeamGuild Plugin.

commands:
  guild:
    aliases: [team]
    description: "TeamGuild - https://github.com/Himmelt/TeamGuild"
    usage: "/guild ..."
permissions:
  guild.admin:
    default: op
