name: TeamGuild
version: 1.1.0
author: Himmelt
main: org.soraworld.guild.TeamGuild
depend: [Violet]
softdepend: [Vault,Essentials,PlayerPoints,PlaceholderAPI]
website: https://github.com/Himmelt/TeamGuild
description: TeamGuild Plugin.
permissions:
  guild.admin:
    default: op
